---
- name: Install postfix and be sure there is no more ssmtp
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - name: ssmtp
      state: absent
    - name: postfix
      state: latest
    - name: libsasl2-modules
      state: latest

- name: Remove any old ssmtp configuration
  file:
    dest: /etc/ssmtp
    state: absent

- name: Copy postfix config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: etc/postfix/main.cf.j2
      dest: /etc/postfix/main.cf
      owner: root
      group: root
      mode: 644
    - src: etc/postfix/sasl_passwd.j2
      dest: /etc/postfix/sasl_passwd
      owner: root
      group: root
      mode: 600
  notify:
    - postmap passwd
    - restart postfix

- name: Set aliases
  lineinfile:
    dest: /etc/aliases
    state: present
    regexp: "^root"
    line: "root: {{ relaymail_root_aliases }}"
  notify:
    - newaliases
