---
- name: Install postfix
  package:
    name:
      - postfix
      - bsd-mailx
      - libsasl2-modules
    state: present

- name: Copy postfix config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: etc/postfix/main.cf.j2
      dest: /etc/postfix/main.cf
      owner: root
      group: root
      mode: "0644"
    - src: etc/postfix/sasl_passwd.j2
      dest: /etc/postfix/sasl_passwd
      owner: root
      group: root
      mode: "0600"
    - src: etc/postfix/sender_canonical_maps.j2
      dest: /etc/postfix/sender_canonical_maps
      owner: root
      group: root
      mode: "0644"
    - src: etc/postfix/header_check.j2
      dest: /etc/postfix/header_check
      owner: root
      group: root
      mode: "0644"
  notify:
    - postmap passwd
    - restart postfix
