---
- name: newaliases
  command: newaliases

- name: postmap passwd
  command: postmap /etc/postfix/sasl_passwd
  environment:
    PATH: "${PATH}:/sbin:/usr/sbin"

- name: restart postfix
  service:
    name: postfix
    state: restarted
